name: Lint

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  Formatting:
    name: Formatting
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10]

    steps:
    - uses: actions/checkout@v3

    - name: Python Setup
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Create Environment
      shell: bash
      run: |
        python -m pip install --upgrade pip
        python -m pip install black

    - name: Lint
      shell: bash
      run: black ccpy --check

  MyPy:
    name: MyPy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10]

    steps:
    - uses: actions/checkout@v3

    - uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: false
        python-version: 3.8
        environment-file: devtools/conda-envs/environment-dev.yaml

    - name: Install
      shell: bash -l {0}
      run: |
        python -m pip install . --no-deps

    - name: Environment Information
      shell: bash -l {0}
      run: |
        conda info
        conda list

    - name: MyPy Check
      shell: bash -l {0}
      run: mypy --ignore-missing-imports mobml

